pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                // 소스코드 체크아웃
                checkout scm
            }
        }
        stage('Build') {
        	steps {
        		script {
                    // JUnit5 테스트 컴파일을 위한 classpath 설정
                    def classpath = "classes:lib/*:/Users/junheejang/.p2/pool/plugins/junit-platform-console-standalone-1.7.1.jar"
                    // 소스 코드 컴파일
                	sh "javac -encoding UTF-8 -cp ${classpath} -d classes misson2/src/*.java"
                }               
            }
        }
        stage('Test') {
            steps {
                script {
                    // JUnit5 테스트 실행을 위한 classpath 설정
                    def classpath = "classes:lib/*:/Users/junheejang/.p2/pool/plugins/junit-platform-console-standalone-1.7.1.jar"
                    // Run JUnit5 Tests
                    sh "java -Dfile.encoding=UTF8 -cp ${classpath} org.junit.platform.console.ConsoleLauncher --scan-classpath > test_results.txt"
                }
            }
        }
    }
    
    post {
        always {
            // 테스트 결과 파일 저장
            archiveArtifacts 'test_results.txt'
            // 특정 폴더에 파일 저장
            sh 'cp test_results.txt /Users/junheejang/git/mission2_software_engineering/result'
            
        }
        failure {
            echo 'Build or test failed'
        }
        success {
            echo 'Build and test succeeded'
        }
    }   
}
