pipeline{
	agent any
	
	stage('Checkout') {
		steps{
			// 소스코드 체아웃
    		checkout scm
    	}
	}
	stage('Build'){
		steps{
			sh 'javac -encoding UTF-8 -d classes misson2/scr/**/*.java'
		}
	}
	stage('Test'){
		steps{
			// JUnit5 테스트 실행을 위한 classpath 설
			def classpath = "classes;lib/;/Users/junheejang/.p2/pool/plugins/junit-platform-console-standalone-1.7.1.jar"
			// Run JUnit5 Test
			bat  'java -cp classes;lib/; /Users/junheejang/.p2/pool/plugins/junit-platform-console-standalone-1.7.1.jar org.junit.platform.console.ConsoleLauncher --scan-classpath >
test_results.txt'
		}
	}
		
	post{
		always {
			archiveArtifacts 'test_results.txt'
		}
		failure{
			echo 'Bulid or test failed'
		}
		success{
			echo 'Build and test succeeded'
		}
	}	
}